### ISSUE TITLE
7.1 ex. code error

### ISSUE THREAD

**Issue by pinhead001** [dabeaz/python-distilled#29]
Tom should be Thomas in the last example on pg. 153 .
Found by Olivia Nelson (age 9)

**Comment by dabeaz** [comment]
The `names[1] = 'Tom'` line is changing `'Thomas'` to `'Tom'` in the list.   There should probably be another line added to show the effect though:

```
>>> names
[ 'Paula', 'Tom', 'Lewis']
>>>
```

Added to errata.  Thanks!
