### ISSUE TITLE
more typos in chapter 10

### ISSUE THREAD

**Issue by wildekat** [dabeaz/python-distilled#33]
Page 308, last paragraph:
`round(x [, n])` Rounds the result of rounding...
Should read: Returns the result

Table 10.9 String Operators and Methods
`s.format_map(m)` Formats `s` with substitutions taking from the mapping `m`
Should read: taken from

Table 10.10 Tuple Operators and Methods
`s + t` Concatenation if `t` is a list.
Should read: if `t` is a tuple

**Comment by dabeaz** [comment]
Added to errata. Thanks!
