### ISSUE TITLE
6.6 wrong decorator

### ISSUE THREAD

**Issue by sergemcdst22** [dabeaz/python-distilled#34]
Hello, thanks for great book, don't know if its in pdf but in o'reilly view "line_receiver" generator is decorated with "consumer" decorator whitch isn't defined anywhere (but when clicking on "view code image" there isn't this decorator anymore so maybe it's only o'reilly viewer mistake)  

 
![decorator](https://user-images.githubusercontent.com/115060717/224515336-3ba15e00-7c4a-407a-9d25-d86f66f60944.png)

**Comment by dabeaz** [comment]
I don't see a `@consumer` decorator in the printed copy.
