### ISSUE TITLE
5.4.3 - Keyword Arguments

### ISSUE THREAD

**Issue by mchion** [dabeaz/python-distilled#37]
For 5.4.3 (on page 103), the following should be corrected:

original
```
func('hello', 3, z=[1, 2], y=22)
func(3, 22, w='hello', z=[1, 2])  # TypeError. Multiple values for x 
```

corrected
```
func(3, 22, w='hello', z=[1, 2]) 
func('hello', 3, z=[1, 2], y=22) # TypeError. Multiple values for y
```

**Comment by dabeaz** [comment]
I don't see this error in my edition.   I see a comment "TypeError. Multiple values for w" which is the same output as the interpreter.
