### ISSUE TITLE
7.7 Inheritance: typo in MyAcount (sic)

### ISSUE THREAD

**Issue by michrag** [dabeaz/python-distilled#39]
In Chapter 7, subchapter "7.7 Inheritance", page 160, in the first code example, the sub class is defined as
`class MyAcount(Account)`
so I guess a `c` is missing in the name.
Typo repeated 5 lines below when instatiating a `MyAcount` object.

I take this opportunity to say that I'm loving this book, it's awesome.

**Comment by dabeaz** [comment]
Added to errata.  Thanks!
