### ISSUE TITLE
6.6 line_receiver must be initialized with r.send(None)

### ISSUE THREAD

**Issue by marcoemorais** [dabeaz/python-distilled#40]
Thank you for writing this book! _Python Distilled_ is a worthy replacement for _Python Essential Reference_.

In section 6.6 the code snippet that demonstrates the enhanced generator `line_receiver` is missing the initialization step `r.send(None)`.

In other words change

from
```
r = line_receiver()
r.send(b'hello')
r.send(b'world\nit ')
r.send(b'works!')
r.send(b'\n')
```

to
```
r = line_receiver()
r.send(None)  # Missing in book.
r.send(b'hello')
r.send(b'world\nit ')
r.send(b'works!')
r.send(b'\n')
```

**Comment by dabeaz** [comment]
My copy has the following line:

```
>>> r.send(None)     # Prime the generator
```

If this is missing in your copy, perhaps you can provide more information.

**Comment by marcoemorais** [comment]
I have the Kindle edition, is there a way to provide a more specific version? I just double checked and the initialization step is still missing in this edition.
