### ISSUE TITLE
6.4 typos in line matching generator 

### ISSUE THREAD

**Issue by marcoemorais** [dabeaz/python-distilled#41]
The code snippet that appears after the generators used to match a pattern in lines read from a file contains some typos that will raise a `NameError`.

Change

from
```
paths = get_paths('.', '*.py')
files = get_files(pypaths)
lines = get_lines(pyfiles)
comments = get_comments(lines)
print_matching(comments, 'spam')
```
to
```
pypaths = get_paths('.', '*.py')  # Replaced paths with pypaths.
pyfiles = get_files(pypaths)  # Replaced files with pyfiles.
lines = get_lines(pyfiles)
comments = get_comments(lines)
print_matching(comments, 'spam')
```

**Comment by dabeaz** [comment]
I'm not seeing the use of variables `pypaths` and `pyfiles` in my printed copy which shows the following code:

```
paths = get_paths('.' '*.py')
files = get_files(paths)
lines = get_lines(files)
comments = get_comments(lines)
print_matching(comments, 'spam')
```

If it  is different your copy, can you provide a bit more information?

**Comment by marcoemorais** [comment]
This is the Kindle edition and I can confirm the typo is still present in this edition. Same as https://github.com/dabeaz/python-distilled/issues/40#issuecomment-2126061642

**Comment by dabeaz** [comment]
Ugh.   My apologies. As author, I'm entirely removed from the process of creating various electronic editions.   However, I just looked at one of the final author review copies they sent me prior to publication and this error is not present.   Did the Kindle edition get created from something even earlier?   I have no idea. Sigh.  

Not sure what I can do here other than to alert the publisher that the Kindle version is weird.
