### ISSUE TITLE
2.7 BooleanExpressionsandTruthValues

### ISSUE THREAD

**Issue by phils4000** [dabeaz/python-distilled#43]
Is there any reason sets are not included in below sentence ?
"When you use an expression to determine a true or false value, True , any nonzero number, a nonempty string, list, tuple, or dictionary is taken to be true. False , zero, None , and empty lists, tuples, and dictionaries evaluate as false."

**Comment by dabeaz** [comment]
I forgot?

**Comment by dabeaz** [comment]
Added to errata.  Thanks!
