### ISSUE TITLE
5.16 `debug` should be after the `/` separator

### ISSUE THREAD

**Issue by kemar** [dabeaz/python-distilled#6]
Section 5.16, pg. 121, in the positional-only arguments example, `debug` should be after the `/` separator:

The signature is:

```diff
-def after(seconds, func, debug=False, /, *args, **kwargs):
+def after(seconds, func, /, *args, debug=False, **kwargs):
```

**Comment by dabeaz** [comment]
Not a typo, but still questionable.   The example is meant to illustrate how keyword arguments using `**kwargs` can be safely accepted without conflicting with other already defined arguments.   If anything, a comment about `debug` no longer being possible to pass as a keyword argument should be added somewhere. Or the example should be rewritten to not include the `debug` argument.

**Comment by physadair** [comment]
If not putting `debug=True` after the `/` separator, the function call in text would failed with the error,

> after(1, add, 1, y=2)
> TypeError: add() missing 1 required positional argument: 'x'

`1` has been assigned to `debug`, not `x`.

**Comment by dabeaz** [comment]
Added to errata. Thanks!
